#
# GitHub-Actions CI
#
# This workflow runs tests for the github-actions implemented
# in `./src/actions/`. It runs both the local version, as well as the latest
# tagged release.
#

name: "GitHub-Actions"

on: [pull_request, push]

jobs:
  test_actions:
    name: "Test Custom Github-Actions"
    runs-on: ubuntu-latest

    services:
      # Provide a local httpd to test the `netwait` action.
      httpd:
        image: "httpd"
        ports:
        - "8080:80"

    steps:
    - name: "Clone Repository"
      uses: actions/checkout@v2

    # Test the NetWait action.
    - name: "Run Local NetWait Action"
      uses: ./src/actions/netwait
      with:
        port: "8080"
    - name: "Run Release NetWait Action"
      uses: osbuild/containers/src/actions/netwait@v1
      with:
        port: "8080"

    # Test the GHCI-OSBuild action.
    - name: "Run Local CI Test Action"
      uses: ./src/actions/ghci-osbuild
      with:
        run: |
          echo Foo
          echo Bar
    - name: "Run Release CI Test Action"
      uses: osbuild/containers/src/actions/ghci-osbuild@v1
      with:
        run: |
          echo Foo
          echo Bar
